# Generated by Django 5.0.6 on 2024-06-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ticket_qr_code_alter_ticket_qr_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
